# TOY_01 

num_sims: 10                # (int) Number of simulations

model:
  name: TOY                 # (str) Name of model
  args:
    global_args:
      state_dim: 1          # (int) State dimension (dx) 
      observation_dim: 1    # (int) Observation dimension (dy) 
      initial_time: 0       # (float) Start time of the simulation
      dt: 0.1               # (float) Time step size
      T_steps: 100          # (int) Number of data assimilation time steps
    local_args:
      initial_noise: 0.1    # (float) Std of noise for initial ensemble sampling
      process_noise: 0.1    # (float) Std of Gaussian noise for forward process 
    
obs_operator:
  name: AbsGauss            # (str) Name of observation operator
  args:
    sigma: 0.1              # (float) Std of Gaussian noise added to observations

sweep_params:
  ensemble_sizes: [50, 100, 200, 250, 300, 500, 1000]
  kde:
    h_x_mins: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
    h_x_maxs: [3, 5, 10, 15, 20, 25, 35, 50]
    h_ys: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]