exp_id: L63_01

num_sims: 10                # (int) Number of simulations

model:
  name: L63            # (str) Name of model
  args:
    global_args:
      state_dim: 3          # (int) State dimension (dx)
      observation_dim: 1    # (int) Observation dimension (dy)
      initial_time: 0       # (float) Start time of the simulation
      T_steps: 1000         # (float) Time step size
      dt: 0.01              # (int) Number of data assimilation time steps
    local_args:
      sigma: 10                       # (float) Model Parameter:  Prandtl number
      rho: 28                         # (float) Model Parameter:  Rayleigh number
      beta: 8/3                       # (float) Model Parameter:  Physical dimensions of the layer
      initial_noise: np.sqrt(10)      # (float) Std of Gaussian noise for initial ensemble sampling
      process_noise: np.sqrt(10)/10   # (float) Std of Gaussian noise for forward process
      integration_dt: 0.01
    

obs_operator:
  name: PartialGauss        # (str) Name of observation operator
  args:
    idx: 2                  # (int) Index of state observed
    sigma: np.sqrt(10)      # (float) Std of Gaussian noise added to observations
